version: "3.8"

services:
  nodejs:
    build:
      context: .
      dockerfile: nodejs/Dockerfile
    ports:
      - "3000:3000"

  flask:
    build:
      context: .
      dockerfile: flask/Dockerfile
    ports:
      - "5000:5000"
