version: '3.8'

services:
  nodejs:
    build:
      context: ./nodejs
    ports:
      - "3000:3000"

  flask:
    build:
      context: ./flask
    ports:
      - "5000:5000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - nodejs
      - flask
