version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1415
      MYSQL_DATABASE: fishdex
      MYSQL_USER: root
      MYSQL_PASSWORD: 1415
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nodejs:
    build: ./nodejs
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1415
      DB_NAME: fishdex

  flask:
    build: ./flask
    ports:
      - "5000:5000"

volumes:
  mysql-data:
